// Copyright 2024-2026 Jonathan Shook
// SPDX-License-Identifier: Apache-2.0

//! nmbrs build script — SRD-85 bundled-workload manifest.
//!
//! The binary is the only catalog assembler, so this is the only
//! generator: it walks the workload source directories and
//! writes one `bundled_workloads.rs` into `OUT_DIR` declaring
//! the full `BUNDLED` table, each entry `include_str!`-ing its
//! yaml — the same embedding mechanism the polydat stdlib uses.
//!
//! Sources (all inside this package, so a crates.io build bundles
//! exactly what a checkout does) and their catalog namespaces / tiers:
//!
//! - `workloads/`                   → curated, top-level names; its
//!   `cql/` subtree (`cql/…`) is included only when a CQL engine
//!   feature is enabled, so the catalog is truthful about what THIS
//!   binary can run (build scripts see their crate's features as
//!   `CARGO_FEATURE_*` env vars)
//! - `examples/workloads/`          → examples tier, `examples/…`
//! - `drivers/`                     → examples tier, `drivers/…`
//!
//! Walk rules: only `.yaml`/`.yml` files; `_`-prefixed files
//! skipped; subdirectories recurse into name segments except
//! `local/` (per-checkout scratch) and `logs/` (session output);
//! catalog names are extension-less; a duplicate catalog name is
//! a build error. A missing source directory is a build error too:
//! an empty catalog must never ship silently.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

struct BundleSpec {
    dir: PathBuf,
    namespace: &'static str,
    tier_expr: &'static str,
    /// Top-level subdirectories of `dir` to leave out of this build.
    skip_top: &'static [&'static str],
}

fn main() {
    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    let cql_enabled = std::env::var_os("CARGO_FEATURE_ENGINE_SCYLLA").is_some()
        || std::env::var_os("CARGO_FEATURE_ENGINE_CASSANDRA_CPP").is_some();

    let specs = vec![
        BundleSpec {
            dir: manifest_dir.join("workloads"),
            namespace: "",
            tier_expr: "nmbrs_workload::catalog::Tier::Curated",
            // The CQL suite rides under `workloads/cql/` and is only
            // truthful when this binary links a CQL engine.
            skip_top: if cql_enabled { &[] } else { &["cql"] },
        },
        BundleSpec {
            dir: manifest_dir.join("examples").join("workloads"),
            namespace: "examples",
            tier_expr: "nmbrs_workload::catalog::Tier::Example",
            skip_top: &[],
        },
        // SRD-109 — driver manifests + their implementation
        // libraries (`drivers/<name>/driver` + siblings). The
        // http adapter is always compiled, so drivers bundle
        // unconditionally. Example tier: `describe drivers` is
        // their discovery surface, not the workload listing.
        BundleSpec {
            dir: manifest_dir.join("drivers"),
            namespace: "drivers",
            tier_expr: "nmbrs_workload::catalog::Tier::Example",
            skip_top: &[],
        },
    ];

    let mut entries: Vec<(String, &'static str, String)> = Vec::new(); // (name, tier, abs_path)
    for spec in &specs {
        println!("cargo:rerun-if-changed={}", spec.dir.display());
        assert!(
            spec.dir.is_dir(),
            "bundled workload source directory missing: {} — the catalog must never ship empty",
            spec.dir.display()
        );
        walk(
            &spec.dir,
            spec.namespace,
            spec.tier_expr,
            spec.skip_top,
            &mut entries,
        );
    }
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    for w in entries.windows(2) {
        assert_ne!(
            w[0].0, w[1].0,
            "bundled workload name collision: `{}` ({} vs {})",
            w[0].0, w[0].2, w[1].2,
        );
    }

    let mut src = String::new();
    let _ = writeln!(src, "/// Generated by nmbrs/build.rs — do not edit.");
    let _ = writeln!(
        src,
        "pub static BUNDLED: &[nmbrs_workload::catalog::BundledWorkload] = &["
    );
    for (name, tier, path) in &entries {
        let _ = writeln!(
            src,
            "    nmbrs_workload::catalog::BundledWorkload {{ \
             name: {name:?}, tier: {tier}, source: include_str!({path:?}) }},"
        );
    }
    let _ = writeln!(src, "];");
    std::fs::write(out_dir.join("bundled_workloads.rs"), src).expect("write bundled_workloads.rs");
}

fn walk(
    dir: &Path,
    namespace: &str,
    tier_expr: &'static str,
    skip_top: &[&str],
    out: &mut Vec<(String, &'static str, String)>,
) {
    let mut children: Vec<_> = std::fs::read_dir(dir)
        .unwrap_or_else(|e| panic!("read_dir {}: {e}", dir.display()))
        .map(|r| r.expect("dir entry"))
        .collect();
    children.sort_by_key(|e| e.file_name());
    for entry in children {
        let path = entry.path();
        let fname = entry.file_name().to_string_lossy().into_owned();
        if path.is_dir() {
            if fname == "local" || fname == "logs" || skip_top.contains(&fname.as_str()) {
                continue;
            }
            let sub_ns = if namespace.is_empty() {
                fname.clone()
            } else {
                format!("{namespace}/{fname}")
            };
            walk(&path, &sub_ns, tier_expr, &[], out);
            continue;
        }
        if fname.starts_with('_') {
            continue;
        }
        let Some(stem) = fname
            .strip_suffix(".yaml")
            .or_else(|| fname.strip_suffix(".yml"))
        else {
            continue;
        };
        println!("cargo:rerun-if-changed={}", path.display());
        let name = if namespace.is_empty() {
            stem.to_string()
        } else {
            format!("{namespace}/{stem}")
        };
        let abs = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("canonicalize {}: {e}", path.display()));
        out.push((name, tier_expr, abs.to_string_lossy().into_owned()));
    }
}
