// Copyright 2024-2026 Jonathan Shook
// SPDX-License-Identifier: Apache-2.0

//! Framing markdown report — bundles summary tables and plot
//! images into a single `summary.md` (or user-named) file
//! that lives next to the metrics db. `nmbrs summary` and
//! `nmbrs plot` both append into this doc by default, so a
//! finished session ends up with one navigable artifact
//! covering every named summary and every named plot.
//!
//! ## File structure
//!
//! Each artifact lives under a level-2 heading whose text is
//! a structured anchor:
//!
//! ```markdown
//! # nmbrs session report
//!
//! _Generated by `nmbrs summary` / `nmbrs plot`._
//!
//! ## summary: recallnmore
//!
//! | Activity | Cycles | … |
//! | --- | --- | --- |
//! | … | … | … |
//!
//! ## plot: recall_at_k10
//!
//! ![recall_at_k10](plot_recall_at_k10.png)
//! ```
//!
//! ## Append vs replace
//!
//! [`upsert_section`] is idempotent: if a heading with the same
//! anchor already exists in the file, its body is replaced;
//! otherwise the section is appended. Re-running `nmbrs summary
//! all` or `nmbrs plot all` over the same db keeps the doc in
//! sync without growing duplicate sections.
//!
//! ## Path resolution
//!
//! Both commands accept `--report <path>` to override. With no
//! flag, the default is `<db_dir>/summary.md` — same directory
//! as the metrics db, named `summary.md`. The runner already
//! writes a per-summary `<name>_summary.md` for each named
//! summary; this companion bundles every artifact into one.

use std::path::Path;

const DOC_HEADER: &str = "# nmbrs session report\n\n\
    _Generated by `nmbrs summary` / `nmbrs plot`. Sections are\n\
    upserted by name — re-running these commands updates each\n\
    section in place rather than appending duplicates._\n\n";

/// How an existing same-name section is handled when writing
/// into a markdown report.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum WriteMode {
    /// `--update-markdown`: replace existing section in place,
    /// preserving its position. New sections are appended.
    /// Position-stable, content-fresh.
    Update,
    /// `--add-to-markdown`: append only when no section by the
    /// same anchor exists. Existing sections are left untouched
    /// (the new figure is *not* added). Use for "I want to
    /// build up a doc and never lose its contents".
    AddIfMissing,
}

/// Write a SRD-46 named section: heading carries a display
/// string plus a stable `{#anchor}` token. The anchor is the
/// canonical item name; lookup ignores the display text so
/// reruns that change figure numbers / labels still find and
/// replace the prior section in place.
pub fn write_named_section(
    report_path: &Path,
    anchor: &str,
    heading_display: &str,
    body: &str,
    mode: WriteMode,
) -> Result<bool, String> {
    let mut current = if report_path.exists() {
        std::fs::read_to_string(report_path)
            .map_err(|e| format!("read '{}': {e}", report_path.display()))?
    } else {
        DOC_HEADER.to_string()
    };
    if !current.starts_with("# ") {
        current = format!("{DOC_HEADER}{current}");
    }

    let new_section = render_section(anchor, heading_display, body);

    let (updated, modified) = match (find_section_by_anchor(&current, anchor), mode) {
        (Some((start, end)), WriteMode::Update) => {
            let mut out = String::with_capacity(current.len() + new_section.len());
            out.push_str(&current[..start]);
            out.push_str(&new_section);
            out.push_str(&current[end..]);
            (out, true)
        }
        (Some(_), WriteMode::AddIfMissing) => (current, false),
        (None, _) => {
            let mut prefix = current;
            while prefix.ends_with("\n\n\n") {
                prefix.pop();
            }
            if !prefix.ends_with("\n\n") {
                prefix.push('\n');
                if !prefix.ends_with("\n\n") {
                    prefix.push('\n');
                }
            }
            (format!("{prefix}{new_section}"), true)
        }
    };

    if !modified {
        return Ok(false);
    }

    if let Some(parent) = report_path.parent()
        && !parent.as_os_str().is_empty()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create dir '{}': {e}", parent.display()))?;
    }
    std::fs::write(report_path, updated)
        .map_err(|e| format!("write '{}': {e}", report_path.display()))?;
    Ok(true)
}

/// Render one `## Heading` section preceded by a portable
/// HTML anchor tag.
///
/// The previous shape used the pandoc-style `{#anchor}`
/// extension after the heading text — terse but only some
/// markdown renderers honour it; many display the literal
/// `{#anchor}` braces in the rendered output. The HTML
/// anchor on its own line is universally understood (every
/// markdown processor passes raw HTML through to the
/// rendered DOM) and disappears from the visible heading.
///
/// Layout:
///
/// ```text
/// <a id="anchor"></a>
/// ## Heading Display
///
/// <body>
/// ```
fn render_section(anchor: &str, heading_display: &str, body: &str) -> String {
    let body_trimmed = body.trim_end_matches('\n');
    format!("<a id=\"{anchor}\"></a>\n## {heading_display}\n\n{body_trimmed}\n\n")
}

/// Like [`write_named_section`] but forces the section to be
/// the FIRST `##` heading in the file (right after the doc
/// header). Used for the auto-injected Details block (SRD-46)
/// so session context always reads at the top.
///
/// If the anchor already exists, its content is replaced in
/// place — same as [`write_named_section`]. If it doesn't
/// exist, the section is inserted directly after the doc
/// header line, before any existing `##` sections.
pub fn write_named_section_first(
    report_path: &Path,
    anchor: &str,
    heading_display: &str,
    body: &str,
) -> Result<bool, String> {
    let mut current = if report_path.exists() {
        std::fs::read_to_string(report_path)
            .map_err(|e| format!("read '{}': {e}", report_path.display()))?
    } else {
        DOC_HEADER.to_string()
    };
    if !current.starts_with("# ") {
        current = format!("{DOC_HEADER}{current}");
    }

    let new_section = render_section(anchor, heading_display, body);

    let updated = if let Some((start, end)) = find_section_by_anchor(&current, anchor) {
        // Replace in place — preserves position whether or not
        // it's currently first.
        let mut out = String::with_capacity(current.len() + new_section.len());
        out.push_str(&current[..start]);
        out.push_str(&new_section);
        out.push_str(&current[end..]);
        out
    } else {
        // Insert after the first `# ` doc-header block (which
        // may span multiple lines until a blank line) and
        // before the first `## ` section.
        let insertion = current
            .find("\n## ")
            .map(|p| p + 1) // land on the `#` of the heading
            .or_else(|| {
                current.find("\n# ").and({
                    // no `## ` yet — append after the header
                    // paragraph (look for the second `\n\n`)
                    None
                })
            })
            .unwrap_or(current.len());
        // Step back to the start of any blank-line padding so
        // the new section is preceded by exactly one blank.
        let mut prefix = current[..insertion].to_string();
        let suffix = current[insertion..].to_string();
        while prefix.ends_with("\n\n\n") {
            prefix.pop();
        }
        if !prefix.ends_with("\n\n") {
            prefix.push('\n');
            if !prefix.ends_with("\n\n") {
                prefix.push('\n');
            }
        }
        format!("{prefix}{new_section}{suffix}")
    };

    if let Some(parent) = report_path.parent()
        && !parent.as_os_str().is_empty()
        && !parent.exists()
    {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create dir '{}': {e}", parent.display()))?;
    }
    std::fs::write(report_path, updated)
        .map_err(|e| format!("write '{}': {e}", report_path.display()))?;
    Ok(true)
}

/// Look up an existing section by its anchor and return the
/// `[start, end)` byte range covering the anchor + heading +
/// body up to (but not including) the next `## ` heading.
///
/// Two forms are recognised:
///
/// - **Modern (HTML anchor on its own line above the
///   heading)** — `<a id="anchor"></a>\n## Heading\n…`. The
///   start byte is the line where the `<a id=…>` lives, so
///   replacement overwrites both the anchor tag and the
///   heading.
/// - **Legacy (pandoc-style `{#anchor}` after the heading
///   text)** — `## Heading {#anchor}\n…`. The start byte is
///   the heading line. Recognised so files written by older
///   builds get migrated to the modern form on the next
///   render touch — no `--rebuild` required for the format
///   migration.
///
/// Returns `None` when no anchor by that name exists in
/// either form.
fn find_section_by_anchor(text: &str, anchor: &str) -> Option<(usize, usize)> {
    // Try the modern form first.
    let html_token = format!("<a id=\"{anchor}\"></a>");
    let mut start_byte: Option<usize> = None;
    for (idx, _) in text.match_indices(&html_token) {
        let line_start = text[..idx].rfind('\n').map(|p| p + 1).unwrap_or(0);
        // Anchor line contains only the tag, then the `## `
        // heading on the next line.
        let line_end = text[line_start..]
            .find('\n')
            .map(|p| line_start + p)
            .unwrap_or(text.len());
        let after = &text[line_end..];
        if after.starts_with("\n## ") {
            start_byte = Some(line_start);
            break;
        }
    }

    // Fall back to the legacy `{#anchor}` form so old files
    // get migrated on the next write.
    if start_byte.is_none() {
        let legacy_token = format!("{{#{anchor}}}");
        for (idx, _) in text.match_indices(&legacy_token) {
            let line_start = text[..idx].rfind('\n').map(|p| p + 1).unwrap_or(0);
            if text[line_start..].starts_with("## ") {
                start_byte = Some(line_start);
                break;
            }
        }
    }

    let start_byte = start_byte?;
    // Walk past the heading line of THIS section so we don't
    // mistake our own `## …` for the next section's. The
    // heading is the first `## ` at or after `start_byte`;
    // we want everything from `start_byte` up to (but not
    // including) the *next* `## ` heading after that.
    let own_heading_offset = text[start_byte..]
        .find("## ")
        .map(|rel| start_byte + rel)
        .unwrap_or(start_byte);
    let after_heading = own_heading_offset + 3;

    let end_byte = if let Some(rel) = text[after_heading..].find("\n## ") {
        let next_heading_byte = after_heading + rel + 1;
        // If an HTML anchor sits on the line directly above
        // the next heading, that anchor "belongs" to the
        // next section — exclude it from this one so a
        // rewrite doesn't strip it. Find the line start
        // immediately preceding `next_heading_byte` and
        // check it.
        let prev_line_end = text[..next_heading_byte].rfind('\n').unwrap_or(0);
        let prior_line_start = text[..prev_line_end]
            .rfind('\n')
            .map(|p| p + 1)
            .unwrap_or(0);
        let prior_line = &text[prior_line_start..prev_line_end];
        if prior_line.trim_start().starts_with("<a id=") && prior_line.trim_end().ends_with("</a>")
        {
            prior_line_start
        } else {
            next_heading_byte
        }
    } else {
        text.len()
    };
    Some((start_byte, end_byte))
}

/// Pretty-print a snake_case canonical name as a heading-friendly
/// title. `recall_at_k10` → `Recall At K10`. Used as a fallback
/// when no `label "…"` directive was supplied.
pub fn prettify_name(name: &str) -> String {
    let mut out = String::new();
    let mut next_upper = true;
    for ch in name.chars() {
        if ch == '_' || ch == '-' {
            out.push(' ');
            next_upper = true;
        } else if next_upper {
            out.extend(ch.to_uppercase());
            next_upper = false;
        } else {
            out.push(ch);
        }
    }
    out
}

/// Build a markdown image reference for a plot file. Uses the
/// file name as the alt text and a path relative to `report_path`
/// when both share a parent — otherwise the absolute path so
/// the doc resolves regardless of where it's opened from.
pub fn image_section_body(report_path: &Path, image_path: &Path) -> String {
    let rel = match (report_path.parent(), image_path) {
        (Some(parent), p) if parent == p.parent().unwrap_or(parent) => p
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_else(|| p.to_string_lossy().into_owned()),
        _ => image_path.to_string_lossy().into_owned(),
    };
    let alt = image_path
        .file_stem()
        .map(|s| s.to_string_lossy().into_owned())
        .unwrap_or_else(|| "plot".into());
    format!("![{alt}]({rel})\n")
}

#[cfg(test)]
mod tests {
    use super::markdown_table;

    /// Pipe positions counted in CHARACTERS. `char_indices` yields BYTE offsets,
    /// which would report a correctly-padded row containing `µ` as misaligned —
    /// measuring the test the same wrong way the code must not.
    fn cols(line: &str) -> Vec<usize> {
        line.chars()
            .enumerate()
            .filter(|(_, c)| *c == '|')
            .map(|(i, _)| i)
            .collect()
    }

    /// Every `|` must land in the same column on every line of a table.
    ///
    /// The report table emitted `|---|---|` beside unpadded cells, so the raw
    /// markdown was a ragged grid — fine once rendered, hard to read as text,
    /// which is how these files are read most of the time.
    #[test]
    fn markdown_table_aligns_every_divider() {
        let header = vec!["p".to_string(), "segments".to_string(), "bytes".to_string()];
        let rows = vec![
            vec![
                "Partition(0/36 [0..100000))".into(),
                "1".into(),
                "489170772".into(),
            ],
            vec!["short".into(), "22".into(), "7".into()],
        ];
        let out = markdown_table(&header, &rows, 1);
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(lines.len(), 4, "header + divider + 2 rows:\n{out}");
        let want = cols(lines[0]);
        for (n, l) in lines.iter().enumerate() {
            assert_eq!(cols(l), want, "line {n} pipes misaligned:\n{out}");
        }
        // The divider is filled, not a bare `---`.
        assert!(
            lines[1].contains("-----"),
            "divider must span the column:\n{out}"
        );
        // Label column left-aligned, value columns right-aligned.
        assert!(
            lines[3].starts_with("| short  "),
            "labels left-align:\n{out}"
        );
        assert!(
            lines[3].contains("|       22 |"),
            "values right-align:\n{out}"
        );
    }

    /// Headings stack one word per line so a column is as wide as its widest
    /// WORD, not its whole name — the point of the exercise.
    #[test]
    fn headings_stack_one_word_per_line() {
        let header = vec!["p".to_string(), "live_bytes_per_ms (K)".to_string()];
        let rows = vec![vec!["x".to_string(), "21.24".to_string()]];
        let out = markdown_table(&header, &rows, 1);
        let lines: Vec<&str> = out.lines().collect();
        // Five heading lines: live / bytes / per / ms / (K), the unit kept whole.
        assert_eq!(
            lines.len(),
            5 + 1 + 1,
            "heading lines + divider + row:\n{out}"
        );
        assert!(lines[0].contains("live"), "{out}");
        assert!(
            lines[4].contains("(K)"),
            "unit stays whole on its own line:\n{out}"
        );
        // Column is 5 wide ("bytes"), not 21 ("live_bytes_per_ms (K)").
        let width = lines[5].split('|').nth(2).unwrap().len() - 2;
        assert_eq!(width, 5, "column should size to its widest word:\n{out}");
        // Bottom-aligned: the short heading's word sits on the last heading line.
        assert!(
            lines[4].starts_with("| p "),
            "short headings bottom-align:\n{out}"
        );
    }

    /// The markdown artifact must stay a real GFM table: one header row, the
    /// delimiter immediately after. Given several header lines a renderer stops
    /// recognising the table and reflows it into a paragraph, losing the very
    /// alignment the columns provide.
    #[test]
    fn gfm_form_keeps_one_header_row() {
        let header = vec!["p".to_string(), "live_bytes_per_ms (K)".to_string()];
        let rows = vec![vec!["x".to_string(), "21.24".to_string()]];
        let out = markdown_table_gfm(&header, &rows, 1);
        let lines: Vec<&str> = out.lines().collect();
        assert_eq!(lines.len(), 3, "header + delimiter + row:\n{out}");
        assert!(
            lines[0].contains("live<br>bytes<br>per<br>ms<br>(K)"),
            "headings wrap via <br>:\n{out}"
        );
        assert!(
            lines[1].chars().all(|c| "|-: ".contains(c)),
            "delimiter row:\n{out}"
        );
        // Every line carries the same cell count, or the table is malformed.
        let cells = |l: &str| l.matches('|').count();
        assert_eq!(cells(lines[0]), cells(lines[1]));
        assert_eq!(cells(lines[0]), cells(lines[2]));
        // Value columns are marked right-aligned for the renderer.
        assert!(
            lines[1].contains(":|"),
            "numeric columns right-align:\n{out}"
        );
    }

    /// Width is counted in characters, not bytes, so a multi-byte unit suffix
    /// doesn't over-pad its column and knock the grid out of true.
    #[test]
    fn markdown_table_measures_characters_not_bytes() {
        let header = vec!["metric".to_string(), "value".to_string()];
        let rows = vec![
            vec!["latency".into(), "12µs".into()], // 'µ' is two bytes
            vec!["count".into(), "9999".into()],
        ];
        let out = markdown_table(&header, &rows, 1);
        let lines: Vec<&str> = out.lines().collect();
        let want = cols(lines[0]);
        for (n, l) in lines.iter().enumerate() {
            assert_eq!(
                cols(l),
                want,
                "line {n} misaligned by byte-width padding:\n{out}"
            );
        }
    }

    use super::*;

    fn tmp_path(name: &str) -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("nmbrs_report_test_{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir.join(name)
    }

    #[test]
    fn add_if_missing_appends_new_sections() {
        let p = tmp_path("add_new.md");
        let _ = std::fs::remove_file(&p);
        let added = write_named_section(
            &p,
            "summary_a",
            "Summary A (table)",
            "first",
            WriteMode::AddIfMissing,
        )
        .unwrap();
        assert!(added);
        let added2 = write_named_section(
            &p,
            "plot_b",
            "Plot B (plot)",
            "second",
            WriteMode::AddIfMissing,
        )
        .unwrap();
        assert!(added2);
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(
            content.contains("<a id=\"summary_a\"></a>"),
            "missing anchor for summary_a: {content}"
        );
        assert!(
            content.contains("<a id=\"plot_b\"></a>"),
            "missing anchor for plot_b: {content}"
        );
        // The pandoc-style `{#…}` form must NOT appear in
        // freshly-written output — it confuses some
        // markdown renderers (literal braces in the heading).
        assert!(!content.contains("{#summary_a}"));
        assert!(!content.contains("{#plot_b}"));
        assert!(content.contains("first"));
        assert!(content.contains("second"));
    }

    #[test]
    fn named_section_writes_anchor_and_kind() {
        let p = tmp_path("named.md");
        let _ = std::fs::remove_file(&p);
        write_named_section(
            &p,
            "recall_at_k10",
            "3. Recall At K10 (plot)",
            "![](plot_recall_at_k10.png)",
            WriteMode::Update,
        )
        .unwrap();
        let content = std::fs::read_to_string(&p).unwrap();
        // HTML anchor on its own line above the heading;
        // heading text is clean (no `{#…}` suffix).
        assert!(
            content.contains("<a id=\"recall_at_k10\"></a>\n## 3. Recall At K10 (plot)"),
            "anchor + heading shape missing: {content}"
        );
        assert!(
            !content.contains("{#recall_at_k10}"),
            "legacy `{{#…}}` form must not appear in fresh output"
        );
    }

    #[test]
    fn named_section_relookup_by_anchor_survives_label_change() {
        let p = tmp_path("relookup.md");
        let _ = std::fs::remove_file(&p);
        write_named_section(
            &p,
            "recall_at_k10",
            "1. Recall At K10 (plot)",
            "first body",
            WriteMode::Update,
        )
        .unwrap();
        // Same anchor, different display heading + body. The
        // anchor-based lookup must still find and replace the
        // earlier section in place.
        write_named_section(
            &p,
            "recall_at_k10",
            "5. Recall@10 reordered (plot)",
            "second body",
            WriteMode::Update,
        )
        .unwrap();
        let content = std::fs::read_to_string(&p).unwrap();
        assert!(
            content.contains("<a id=\"recall_at_k10\"></a>\n## 5. Recall@10 reordered (plot)"),
            "new heading missing: {content}"
        );
        assert!(
            content.contains("second body"),
            "new body missing: {content}"
        );
        assert!(
            !content.contains("first body"),
            "stale body retained: {content}"
        );
        // Exactly one anchor + one heading for this anchor.
        assert_eq!(content.matches("<a id=\"recall_at_k10\"></a>").count(), 1);
    }

    #[test]
    fn legacy_pandoc_anchor_format_is_migrated_on_rewrite() {
        // Operator already has a markdown report whose
        // sections were written by an older build using
        // `## Title {#anchor}`. The new writer must find
        // the section by its anchor, replace it with the
        // HTML-anchor form, and leave a clean file.
        let p = tmp_path("migrate_legacy.md");
        let _ = std::fs::remove_file(&p);
        let legacy = "# Report\n\n## 1. Old Title {#legacy_anchor}\n\nold body\n\n";
        std::fs::write(&p, legacy).unwrap();

        write_named_section(
            &p,
            "legacy_anchor",
            "1. Migrated Title",
            "fresh body",
            WriteMode::Update,
        )
        .unwrap();

        let content = std::fs::read_to_string(&p).unwrap();
        assert!(
            content.contains("<a id=\"legacy_anchor\"></a>"),
            "expected migrated HTML anchor; got: {content}"
        );
        assert!(
            !content.contains("{#legacy_anchor}"),
            "legacy form should be gone after rewrite; got: {content}"
        );
        assert!(content.contains("fresh body"));
        assert!(!content.contains("old body"));
    }

    #[test]
    fn prettify_simple() {
        assert_eq!(prettify_name("recall_at_k10"), "Recall At K10");
        assert_eq!(prettify_name("p99-latency"), "P99 Latency");
        assert_eq!(prettify_name("recall"), "Recall");
    }

    #[test]
    fn image_body_uses_relative_path_when_colocated() {
        let report = std::path::Path::new("/tmp/sess/summary.md");
        let img = std::path::Path::new("/tmp/sess/plot_recall.png");
        let body = image_section_body(report, img);
        assert!(
            body.contains("![plot_recall](plot_recall.png)"),
            "got: {body}"
        );
    }
}

/// Render a markdown table with every `|` in the same column.
///
/// A rendered table looks the same whether or not the source is padded, but these
/// `.md` files are read as text at least as often as they are rendered, and a
/// ragged grid is hard to scan. Cells are padded to the widest entry in their
/// column and the divider is filled to match.
///
/// `right_align_from` is the first column index to right-align — label columns
/// before it stay left-aligned. Pass `header.len()` to left-align everything.
///
/// Widths count CHARACTERS, not bytes: a unit suffix like `µs` is two bytes and
/// one column, so byte length would over-pad whichever column it lands in.
/// Split a heading into the words it stacks as.
///
/// `snake_case` segments become separate words; a trailing unit annotation
/// (`(G)`, `(min)`, `(UTC)`) stays whole on its own line, being a unit rather
/// than a word of the name.
fn split_heading(heading: &str) -> Vec<String> {
    let (name, unit) = match heading.rsplit_once(" (") {
        Some((n, u)) => (n, Some(format!("({u}"))),
        None => (heading, None),
    };
    // Whitespace splits first; snake_case then splits per word — but
    // definition tokens (`last(result_success)`, `span()`) and
    // provenance tokens (`@phase_name`) stay ATOMIC, or the header
    // stack would shred the very definition it exists to show.
    let mut words: Vec<String> = Vec::new();
    for tok in name.split_whitespace() {
        if tok.contains('(') || tok.starts_with('@') {
            words.push(tok.to_string());
        } else {
            words.extend(tok.split('_').filter(|w| !w.is_empty()).map(str::to_string));
        }
    }
    if words.is_empty() {
        words.push(name.to_string());
    }
    if let Some(u) = unit {
        words.push(u);
    }
    words
}

/// The same table as [`markdown_table`], but a VALID GitHub-Flavored-Markdown
/// table: exactly one header row, delimiter immediately after.
///
/// GFM allows only one header row, so the stacked form — five heading lines
/// before the delimiter — stops being recognised as a table at all and renders
/// as a reflowed paragraph, losing the alignment the stacking was for. Here the
/// heading words are joined with `<br>`, which GFM renders as line breaks inside
/// the cell, so the heading still wraps to one word per line when rendered.
///
/// Data cells are padded to the column's display width (widest word or widest
/// value). The heading cell carries its `<br>` markup and is therefore longer
/// than that in the raw text, so the header row's pipes sit right of the data
/// rows' — unavoidable, since the markup is invisible only once rendered, and
/// the rendered view is the one this form exists to serve.
pub(crate) fn markdown_table_gfm(
    header: &[String],
    rows: &[Vec<String>],
    right_align_from: usize,
) -> String {
    let header_lines: Vec<Vec<String>> = header.iter().map(|h| split_heading(h)).collect();
    let mut widths: Vec<usize> = header_lines
        .iter()
        .map(|words| words.iter().map(|w| w.chars().count()).max().unwrap_or(0))
        .collect();
    for row in rows {
        for (i, cell) in row.iter().enumerate() {
            if i < widths.len() {
                widths[i] = widths[i].max(cell.chars().count());
            }
        }
    }

    let mut out = String::new();
    out.push('|');
    for words in header_lines.iter() {
        out.push_str(&format!(" {} |", words.join("<br>")));
    }
    out.push('\n');
    out.push('|');
    for (i, w) in widths.iter().enumerate() {
        // Alignment markers so the rendered table right-aligns its numbers, the
        // same distinction the padded form makes with spaces.
        if i < right_align_from {
            out.push_str(&format!("-{}-|", "-".repeat(*w)));
        } else {
            out.push_str(&format!("-{}:|", "-".repeat(*w)));
        }
    }
    out.push('\n');
    for row in rows {
        out.push('|');
        for (i, cell) in row.iter().enumerate() {
            if i >= widths.len() {
                continue;
            }
            if i < right_align_from {
                out.push_str(&format!(" {:<w$} |", cell, w = widths[i]));
            } else {
                out.push_str(&format!(" {:>w$} |", cell, w = widths[i]));
            }
        }
        out.push('\n');
    }
    out
}

pub(crate) fn markdown_table(
    header: &[String],
    rows: &[Vec<String>],
    right_align_from: usize,
) -> String {
    // Headings stack one WORD per line, so a column is only as wide as its widest
    // single word rather than its whole name. `live_bytes_per_ms (K)` costs 21
    // columns on one line and 6 across four — and these tables are long names over
    // short numbers, so the name was setting the width nearly everywhere.
    let header_lines: Vec<Vec<String>> = header.iter().map(|h| split_heading(h)).collect();
    let header_depth = header_lines.iter().map(Vec::len).max().unwrap_or(1);

    let mut widths: Vec<usize> = header_lines
        .iter()
        .map(|words| words.iter().map(|w| w.chars().count()).max().unwrap_or(0))
        .collect();
    for row in rows {
        for (i, cell) in row.iter().enumerate() {
            if i < widths.len() {
                widths[i] = widths[i].max(cell.chars().count());
            }
        }
    }

    let mut out = String::new();
    // Bottom-aligned: shorter headings are padded at the TOP so every heading's
    // last word sits directly above the divider, beside the values it labels.
    for line in 0..header_depth {
        out.push('|');
        for (i, words) in header_lines.iter().enumerate() {
            let pad_top = header_depth - words.len();
            let text = if line < pad_top {
                ""
            } else {
                words[line - pad_top].as_str()
            };
            out.push_str(&format!(" {:<w$} |", text, w = widths[i]));
        }
        out.push('\n');
    }
    out.push('|');
    for w in &widths {
        out.push_str(&format!("-{}-|", "-".repeat(*w)));
    }
    out.push('\n');
    for row in rows {
        out.push('|');
        for (i, cell) in row.iter().enumerate() {
            if i >= widths.len() {
                continue;
            }
            if i < right_align_from {
                out.push_str(&format!(" {:<w$} |", cell, w = widths[i]));
            } else {
                out.push_str(&format!(" {:>w$} |", cell, w = widths[i]));
            }
        }
        out.push('\n');
    }
    out
}
